# openapi2-functions.yaml
swagger: '2.0'
info:
  title: anz-proof-of-reserve exposing proof-of-reserve-api
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /balance:
    get:
      summary: Give balance of an account
      operationId: balance
      x-google-backend:
        address: https://australia-southeast1-level-harbor-348605.cloudfunctions.net/proof-of-reserve
      responses:
        '200':
          description: A successful response
          schema:
            $ref: "#/definitions/Balance"
definitions:
  Balance:
    type: "object"
    properties:
      status:
        type: "string"
        enum:
        - "success"
        - "error"
      balance:
        type: "object"
        properties:
          accountNumber:
            type: "string"
          accountSystem:
            type: "string"
          currencyCode:
            type: "string"
          country:
            type: "string"
          effectiveDate:
            type: "string"
          availableBalance:
            type: "string"
