# openapi2-functions.yaml
swagger: '2.0'
info:
  title: proof-of-reserve external adapter for chain-link
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /balance:
    get:
      summary: Give balance of an account
      operationId: balance
      x-google-backend:
        address: https://australia-southeast1-level-harbor-348605.cloudfunctions.net/balance-check-test
      responses:
        '200':
          description: A successful response
          schema:
            type: string
